name: Upload powershell web service

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
          source-url: https://nuget.pkg.github.com/Sarpsborg-kommune/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.JTN70_TOKEN}}
      - run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release
      #- name: Store github token
      #  run: dotnet nuget add source --username jtn70 --password ${{ secrets.JTN70_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Sarpsborg-kommune/index.json"
      - name: Publish the package to github
        run: dotnet nuget push PowershellWebService/bin/Release/*.nupkg
